### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by emaildano** [instantpage/instant.page#34]
I love the idea of this and so far it's off to a good start.

I'm working with Shifter (getshifter.io) which is a static site generator for WordPress and hosting provider. I want to see if there are ways to make the static sites we're creating faster or at least improve the interactivity.

My questions are:

**1. Does this library factor in the type of content it's fetching?**

It's possible the type or fetch `as` is not being used. Maybe it is and I'm not seeing it. I'm not sure if the type would be `as=document` or `as=fetch`.

Refs:
- https://twitter.com/DasSurma/status/808791438171537408
- https://medium.com/reloading/preload-prefetch-and-priorities-in-chrome-776165961bbf
- > If you don’t supply a valid “as” when specifying what to preload, for example, scripts, you will end up fetching twice.
- https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content

**2. Are you planning on introducing an API for this library?**

With an API you can add a few simple options such as the time to prefetch, whether you need to hover at all and instead use the viewport as a trigger, etc.

Refs:
- https://github.com/nozzle/react-static/blob/daf2d6bd17c3365d22beee086d0fb79e7431ec91/docs/api.md#useprefetch
- 

**3. Avoid repeat fetching**

Maybe this is relate to the first question. On repeat hover, the library will refetch the page. Can this be avoided? Adding the fetch as `text/html` is a possible fix or some JS to skip it.

Maybe the Quicklink project already does a lot of this but I love how simple the script you've created is.

**Comment by dieulot** [comment]
Regarding the `as` attribute it’s only necessary when using preload, instant.page uses prefetch.

The “API” is done via attributes as detailed on https://instant.page/blacklist so that the library can be loaded asynchronously.

I don’t plan on adding viewport preloading because Quicklink already does that, and I believe it’s not as good a trade-off regarding speed versus server load.

The way to avoid repeat fetching is to add cache headers to the HTML being served. Repeat fetching could be avoided in the script itself but I don’t plan on doing that because cache headers are a better fit for it, and repeat fetching happens rarely enough that it’s not a big worry to have.
