### ISSUE TITLE
Scripts loads http not https

### ISSUE THREAD

**Issue by josefzacek** [instantpage/instant.page#8]
Visit https://www.jawaireland.ie/, hover over the header menu links. Insecure content blocked icon appears in search bar

<img width="1339" alt="screen shot 2019-02-11 at 16 31 57" src="https://user-images.githubusercontent.com/2744855/52577664-7ea0b700-2e1a-11e9-8f23-f6ba908d9431.png">

**Comment by scitronboy** [comment]
Try changing it to

    <script src="https://instant.page/1.1.0" type="module" integrity="sha384-EwBObn5QAxP8f09iemwAJljc+sU+eUXeL9vSBw1eNmVarwhKk2F9vBEpaN9rsrtp"></script>

By the way, your website doesn't warn _my_ (chrome) browser about "unsafe scripts"

**Comment by josefzacek** [comment]
@scitronboy I took the script from https://instant.page/ page which I believe is the latest version

**Comment by batbyR** [comment]
Hi @josefzacek!

Adding a slash at the end of your header menu links solved the problem on my machine.

````
<li class="nav-item">
  <a href="/models/" class="nav-link">Models</a>
</li>
````

**Before:**

![image](https://user-images.githubusercontent.com/13064661/52822982-a65e7c00-30b3-11e9-94cb-484cbbf2562f.png)


**After:**

![image](https://user-images.githubusercontent.com/13064661/52823017-cb52ef00-30b3-11e9-8edc-b2edb3838c7f.png)

The prefetching requests are now successfull and insecure content warnings disappear.

You seem to force the slash at the end when visiting [https://jawaireland.ie/models](https://jawaireland.ie/models) for example. Maybe it makes the prefecthing request fail. But I have not the root cause yet.

Tell me if this solution fixes the problem for you! 🤞

**Comment by josefzacek** [comment]
@batbyR hey Romain, thanks I mil for your help, it fixed the problem 👍🏾

Josef
